import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'tier-list',
    'frequently-asked-questions',
    {
      type: 'category',
      label: 'Hero Overviews',
      items: [{ type: 'autogenerated', dirName: 'hero' }],
    },
    {
      type: 'category',
      label: 'Gameplay Guides',
      items: [{ type: 'autogenerated', dirName: 'gameplay-guides' }],
    },
    {
      type: 'category',
      label: 'Event Guides',
      items: [{ type: 'autogenerated', dirName: 'event-guides' }],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [{ type: 'autogenerated', dirName: 'resources' }],
    },
    'feedback',
  ],
}

export default sidebars
