type RowType = {
  'Star Passive': string
  [key: string]: string
}

type HeroesType = {
  [key: string]: RowType | null
}

const data: HeroesType = {
  'Arcane Mage': {
    'Star Passive': '2x Proj Chance',
    10: '+1 Penetration to Arcane Wand Projectiles',
    20: 'Mind Control: Enemies hit by Arcane Wand are slowed by 30% / 36% / 42% / 48% for 2s',
    30: '+2.5% Projectile Speed',
    40: 'Barrage: Arcane Wand has 15% / 18% / 21% / 24% chance to double projectiles',
    50: '+1 Magical Projectile',
    60: '+12.5% Damage',
    70: '-5% Cooldown',
    80: 'Trinity: Defeating enemies fills a meter that spawns a Trinity around you dealing 200% / 240% / 280% / 320% weapon damage per hit',
    90: '+1 Penetration to Arcane Wand projectiles',
    100: '+1 Magical Projectile',
    120: '+15% Projectile speed',
    140: '+1 Magical Projectile',
  },
  Knight: {
    'Star Passive': 'Armor',
    10: '+50% HP/min Regeneration',
    20: 'Whirl Wind: Release a spin attack on every 5th sword attack, dealing 200% / 250% / 300% / 350% weapon damage',
    30: '+25 Health',
    40: 'GiantSlayer: The sword deals 100% /140% / 180% / 220% extra damage to elite enemies and bosses',
    50: '+10% Area of Effect',
    60: '+2.5% Area of Effect',
    70: '+50 Health',
    80: 'Deflective Barrier: Sword hits fill a meter that increases armor drastically and incoming damage is reflected with a 800% multiplier',
    90: '+15% Area of Effect',
    100: '+10 Armor',
    120: '+15% Damage to elite enemies and bosses',
    140: '+7.5% Damage to elite enemies and bosses',
  },
  'Dark Ranger': {
    'Star Passive': 'Damage to Slowed',
    10: '-5% Cooldown',
    20: 'Explosive Arrows: Hunting Bow has a 25% /30% / 35% / 40% chance of making enemies explode on death',
    30: '+2.5% Critical Hit Chance',
    40: 'Wild Thorns: Enemies hit by the bow get entangles in thorns, slowing them by 50% / 55% / 60% / 65% for 2s',
    50: '+1 Physical Projectile',
    60: '+12.5% Damage',
    70: '+5% Critical Hit Chance',
    80: 'Arrow Storm: Bow hits fill a meter causing arrows to fall from the sky dealing 300% / 350% / 400% / 450% weapon damage',
    90: '+35% Damage',
    100: '+7.5% Projectile Speed',
    120: '-5% Cooldown',
    140: '+3% Critical Hit Chance',
  },
  'Crazy Tinkerer': {
    'Star Passive': 'XP Bonus',
    10: '+1 Starting Upgrade',
    20: 'Napalm Trail: Mines leave burning areas after exploding, damaging enemies that pass through for 100% /140% / 180% / 220% weapon dmg / s',
    30: '+5% Movement Speed',
    40: 'Overheat: 10% / 12% / 14% / 16% Chance to increase movement speed and reduce cooldown by 20% for 5s',
    50: '+10% Area of Effect',
    60: '+12.5% Damage',
    70: '+10% Effect Duration',
    80: 'Gatling Gun: Mine hits fill a meter, equipping a gatling gun dealing 1200% / 1600% / 2000% / 2400% weapon damage',
    90: '+35% Damage',
    100: '+5% Area of Effect',
    120: '+10% Damage to burning enemies',
    140: '+7.5% Area of Effect',
  },
  'Fire Wizard': {
    'Star Passive': 'Damage to Burning',
    10: '+25% Damage',
    20: 'Ignite: Enemies that are hit by the fire staff start burning for 2.5s for 50% /60% / 70% / 80% weapon damage / second',
    30: '+2.5% Area of Effect',
    40: 'Scorched Earth: Enemies that die while burning leave a burning area behind that damages enemies for 50% / 60% / 70% / 80% weapon damage',
    50: '+1 Magical Projectile',
    60: '+12.5% Damage',
    70: '+5% Critical Hit Chance',
    80: 'Burning Air: Burning enemies fills a meter that all enemies start burning automatically for 10s for 100% / 120% / 140% / 160% weapon damage per second',
    90: '+15% Area of Effect',
    100: '+ 7.5% Effect Duration',
    120: '+5% Critical Hit Chance',
    140: '+5% Damage to burning enemies',
  },
  'Frost Wizard': {
    'Star Passive': 'Damage to Frozen',
    10: '+25% Damage',
    20: 'Cold Hands: +10% / 12% / 14% / 16% Ice Gauntlets freeze chance',
    30: '+2.5% Effect Duration',
    40: 'Shatter: Frozen enemies that die have a 40% / 45% / 50% / 55% chance of exploding',
    50: '+1 Magical Projectile',
    60: '+12.5% Damage',
    70: '+20% Damage to frozen enemies',
    80: 'Blizzard: Freezing enemies fills a meter, causing ice projectiles to freeze and damage enemies on screen for 100% / 140% / 180% / 220% weapon damage',
    90: '+15% Effect Duration',
    100: '+4% XP Bonus',
    120: '+15% Status Effect Duration',
    140: '+10% Damage to frozen enemies',
  },
  Blademaster: {
    'Star Passive': 'Critical Hit Chance',
    10: '+25% Damage',
    20: 'Deep Cuts: Katana hits cause bleeding, dealing 50% / 60% / 70% / 80% weapon damage / second over 5 seconds',
    30: '+5 Evasion',
    40: 'SwordMaster: Critical Hits with Katana deal 300% / 350% / 400% / 450% Damage',
    50: '+5% Critical Hit Chance',
    60: '+12.5% Damage',
    70: '+10 Evasion',
    80: 'BladeStorm: Crits with Katana fills a meter, turning into a bladestorm for 5s dealing 100% / 125% / 150% / 175% weapon damage over time',
    90: '+35% Damage',
    100: '+3.5% Critical Hit Chance',
    120: '-5% Cooldown',
    140: '+4% Critical Hit Chance',
  },
  'Spirit Shaman': {
    'Star Passive': 'Regeneration',
    10: '+50 Health',
    20: 'Spirit Link: The Spirit Staff aura increase beasts attack speed and movement speed by 30% / 34% / 38% / 42%',
    30: '+15% HP / min Regeneration',
    40: 'Thorn Skin: Beasts reflect 50% / 60% / 70% / 80% of incoming damage onto enemies around them',
    50: '+10% Area of Effect',
    60: '+25 Health',
    70: '+50% HP / min Regeneration',
    80: 'Spirit Orbs: Using Spirit Staff fills a meter and rotating Spirit Orbs spawn around beasts, dealing 800% / 1000% / 1200% / 1400% beast damage',
    90: '+15% Effect Duration',
    100: '+20% Damage',
    120: '+15% Area of Effect',
    140: '+25% HP / min Regeneration',
  },
  Paladin: {
    'Star Passive': 'Pushback',
    10: '+10% Area of Effect',
    20: 'Holy Shield: 5% Chance on attack to get a shield for 3s /3.5s / 4s / 4.5s',
    30: '+10% Pushback',
    40: 'Holy Wrath: Every 5th hammer attack has +200% pushback and 150% / 160% / 170% / 180% area',
    50: '+25% Damage',
    60: '+2.5% Area of Effect',
    70: '+10% Armor',
    80: 'Judgement: Pushing back enemies fills a meter causing several explosions that damages enemies on screen for 500% / 600% / 700% / 800% weapon damage',
    90: '+7.5% XP Bonus',
    100: '+40% Reflection of incoming damage onto nearby enemies',
    120: '+15% Area of Effect',
    140: '+80% Reflection of incoming damage onto nearby enemies',
  },
  Reaper: {
    'Star Passive': 'Area of Effect',
    10: '+10% Area of Effect',
    20: 'Shadow Step: 5% / 6% / 7% / 8% Chance on attack to get 100% evasion and increased movement speed for 3s',
    30: '+5% Movement Speed',
    40: 'Cripple: Attacks slow enemies by 25% / 28% / 31% / 34% for 2s',
    50: '+25% Damage',
    60: '+12.5% Damage',
    70: '+10 Evasion',
    80: 'HellGate: Scythe hits fill a meter that opens a gate to hell, pulling in enemies, increasing damage by 300% / 340% / 380% / 420% as well as evasion, attack speed and area',
    90: '+3% Instant Kill Chance',
    100: '"-2.5% Cooldown',
    120: '+2.5% Chance for enemies to explode on death',
    140: '+10 Evasion',
  },
  'Pirate Queen': {
    'Star Passive': 'Projectile Speed',
    10: '+10% Projectile Speed',
    20: 'Stun Bullets: Enhanced ammunition that has a 20% / 24% / 28% / 32% chance to inflict stun',
    30: '+2.5% Effect Duration',
    40: 'Fast Bullets: 15% Chance to shoot bullets with 150% / 175% / 200% / 225% speed and 250% duration',
    50: '+1 Physical Projectile',
    60: '+2.5% Projectile Speed',
    70: '+2% Instant Kill Chance',
    80: 'Crimson Whirl: Killing enemies fills a meter that unleashes a whirlwind of crimson bullets, dealing 100% / 120% / 140% / 160% weapon damage',
    90: '+15% Effect Duration',
    100: '+1% Instant Kill Chance',
    120: '+5% Critical Hit Chance',
    140: '+5% Projectile Speed',
  },
  Warlock: {
    'Star Passive': '2x Proj Chance',
    10: '+10% Area of Effect',
    20: 'Demonic Curse: Imp-Hit enemies are cursed, spreading 100% / 120% / 140% / 160% Demon Staff damage to nearby foes',
    30: '+2.5% Effect Duration',
    40: 'Entrapping Hex: Imp attacks slow afflicted enemy and surrounding foes by 60% / 65% / 70% / 75% for 5s',
    50: '+25% Damage',
    60: '+5% Status Effect Duration',
    70: '+10% Status Effect Duration',
    80: 'Infernal: Hitting enemies with Demon Staff fills a mater (10x when hitting cursed), summoning an Infernal, releasing shockwaves that curse and dmg enemies for 100% / 120% / 140% / 160% weapon dmg',
    90: '-5% Cooldown',
    100: '+1 Magical Projectile',
    120: '+1 Magical Projectile',
    140: '+10% Status Effect Duration',
  },
  Barbarian: {
    'Star Passive': 'Extra Rage Duration',
    10: '+0.5% extra dmg for every 1% of missing health',
    20: 'Unleashed Fury: Every 30 / 28 / 26/ 24 hits with axes, gain rage for duration of 6 hits with axes (rage is applied to all weapons)',
    30: '+12.5% Damage',
    40: 'Master of Rage: Rage effects additionally increase area by 20% / 22% / 24% / 26%, armor and movement speed',
    50: '+10% Area of Effect',
    60: '+0.2% Extra Damage for every 1% missing health',
    70: '+5% Critical Hit Chance',
    80: 'Go Berserk: Killing enemies fills a meter that increases damage by 50%, 60%, 70%, 80%. Size, attack speed and movement increase. Zoom decreases.',
    90: '-5% Cooldown',
    100: '-2.5% Cooldown',
    120: '+25% Damage',
    140: '+5% Chance for a Critical Hit to deal 4x Damage',
  },
  'Big Game Hunter': {
    'Star Passive': '2x Proj Chance',
    10: '+10% Damage to elite enemies and bosses',
    20: 'Dead Zone: Shotgun shots to nearby enemies have a 50% / 60% / 70% / 80% Crit Chance',
    30: '+2.5% Pushback',
    40: 'Scatter Shot: Every 8 shots, Shotgun projectiles increase by 100% / 120% / 140% / 180% and stun enemies for 2s',
    50: '+10% Pushback',
    60: '+2.5% Projectile Speed',
    70: '-5% Cooldown',
    80: 'Thrill of The Hunt: Killing enemies with Shotgun fills a meter, decreasing cooldown by -50% / -55% / -60% / -65% and projectiles ricochet',
    90: '+15% Damage to elite enemies and bosses',
    100: '+5% Damage to elite enemies and bosses',
    120: '+1 Physical Projectile',
    140: '+10% Damage to elite enemies and bosses',
  },
  'Clockwork Mage': {
    'Star Passive': 'Cooldown',
    10: '+10% Area of Effect',
    20: 'Time Manipulation: Hitting enemies with main weapon slows them by 40% / 45% / 50% / 55% for 3s',
    30: '+2.5% Area of Effect',
    40: 'Clockwork Bombs: 20% chance to put a bomb on them which explodes for 100% / 120% / 140% / 160% weapon dmg after 0.5s or foe dies',
    50: '+10% Projectile Speed',
    60: '+12.5% Damage',
    70: '+10% Damage to slowed enemies',
    80: 'Quantum Rift: Slowing enemies fills a meter that slows all enemies by 80% in a big radius around you, decreases cooldown by -20% / -25% / -30% / -35% and increases hero movement speed',
    90: '+1 Magical Projectile',
    100: '+2.5% Damage to slowed enemies',
    120: '-5% Cooldown',
    140: '+5% XP Bonus',
  },
  Monk: {
    'Star Passive': 'Evasion',
    10: '+10% Effect Duration',
    20: 'Pressure Wave: Every 20 / 19 / 18 / 17 hits with Quarterstaff creates a pressure wave pushing enemies away',
    30: '+5 Evasion',
    40: 'Air Shield: Every 30 / 29 / 28 / 27 hits with Quarterstaff creates an air shield around Monk, protecting him for 3s',
    50: '-5% Cooldown',
    60: '+12.5% Damage',
    70: '+10% Pushback',
    80: 'Air Bending: Hitting enemies with Quarterstaff fills a meter causing Monk to spin it rapidly, making him faster, enemies slow and deals 400% / 450% / 500% / 550% weapon dmg/s',
    90: '+15% Area of Effect',
    100: '+10% Pushback',
    120: '+1 Starting Upgrade',
    140: '+10 Evasion',
  },
  'Tide Warden': {
    'Star Passive': 'Damage to Slowed',
    10: '+10% Area of Effect',
    20: 'Water Barricade: Trident attacks slow enemies by 30% / 35% / 40% / 45%',
    30: '+2.5% XP Bonus',
    40: 'Trident Wave: Every 13 / 12 / 11 / 10 attacks, waves push enemies back and deal 100% damage',
    50: '+10% Effect Duration',
    60: '+12.5% Damage',
    70: '+10% Pushback',
    80: 'Deadly Flood: Killing enemies fills a meter, flooding a big area, slowing enemies inside by 75% & dealing 400% / 460% / 520% / 580% weapon dmg/s. Increase movement speed by 30%',
    90: '+10% Damage to slowed enemies',
    100: '+15% HP / min Regeneration',
    120: '-5% Cooldown',
    140: '+5% Damage to slowed enemies',
  },
  Assassin: {
    'Star Passive': 'Status Effect Damage',
    10: '-10% Cooldown',
    20: 'Poison Cloud: Shurikens have 10% chance to trigger poison cloud explosion, poisoning enemies for 200% / 250% / 300% / 350% weapon dmg/s for 3s',
    30: '+5% Status Effect Duration',
    40: 'Slow Death: Shurikens make enemies bleed for 100% / 150% / 200% / 250% weapon dmg/s for 3s',
    50: '+1 Physical Projectile',
    60: '+12.5% Damage',
    70: '+15% Status Effect Duration',
    80: 'Shuriken Tornado: Killing enemies fills a meter, spinning tornado that increases evasion to 90%, dealing 600% / 800% / 1000% / 1200% weapon dmg/s in an area, cd decreased by -30%',
    90: '+25% Status Effect Damage',
    100: '+5% Status Effect Damage',
    120: '+5% Critical Hit Chance',
    140: '+10% Status Effect Duration',
  },
  'Frost Queen': {
    'Star Passive': 'Dmg to Frozen',
    10: '+5% Freeze Chance',
    20: 'Frost Vulnerability: Consecutive hits on a frozen enemy increase damage by 10% / 11% / 12% / 13%/hit stacking 10x',
    30: '+5% Damage to frozen enemies',
    40: 'Thaw: Enemies that come out of freeze are slowed by 60% / 65% / 70% / 75% for 3s',
    50: '+15% Area of Effect',
    60: '+5% Status Effect Duration',
    70: '+20% Damage to frozen enemies',
    80: 'Long Winter: Freezing enemies fills a meter, enemies in a big area start slowing till frozen after 1.5s for 10s. If frozen enemies die in this area, they explode for 500% / 600% / 700% / 800% weapon dmg',
    90: '+15% Status Effect Duration',
    100: '+5% Damage to slowed enemies',
    120: '+5% Freeze Chance',
    140: '+1 Magical Projectile',
  },
  Oracle: {
    'Star Passive': '+Effect Duration',
    10: '+25% Damage',
    20: 'Astral Radiance: Inflicts 40% / 45% / 50% / 55% weapon dmg every 2s to enemies next to the Orb',
    30: '+15% HP / min Regeneration',
    40: 'Nova: Unleash a 360 degrees pressure wave dealing 300% / 400% / 500% / 600% weapon dmg every 20 attacks',
    50: '10% Area of Effect',
    60: '+2.5% Effect Duration',
    70: '+15% Effect Duration',
    80: 'Spectral Cascade: Killing enemies fills a meter, releasing Orbs in all directions, travel and bouncing off walls dealing extra 50% / 60% / 70% / 80% weapon dmg',
    90: '+1 Magical Projectile',
    100: '+4% XP Bonus',
    120: '+1 Starting Upgrade',
    140: '+5% Area of Effect',
  },
  Artificer: {
    'Star Passive': 'Projectile Speed',
    10: '+25% Damage',
    20: 'Charged Blades: Each hit has a 10% / 11% / 12% / 13% chance to spawn additional blade that lasts 5s. Spawn chance is halved for each active additional blade',
    30: '+2.5% Projectile Speed',
    40: 'Energy Infusion: When thee are 5 or more active extra blades, a damaging wave is emitted every 2s, dealing 150% / 175% / 200% / 225% weapon dmg',
    50: '+1 Projectile',
    60: '+2.5% Projectile Speed',
    70: '+1 Starting Upgrade',
    80: 'Blade Dance: Killing enemies fills a meter that triggers several effects: Blade count +5, proj spd +100%, dmg +50% / 70% / 90% / 110% and hero pulls enemies and dodge attacks',
    90: '+5% Critical Hit Chance',
    100: '+5% Projectile Speed',
    120: '+15% Projectile Speed',
    140: '+1 Physical Projectile',
  },
  'Santa Claus': {
    'Star Passive': '+Coin Bonus',
    10: '+20% Chance to find Lucky Wheel item',
    20: 'Holiday Looter: During December +20% Coin Bonus, +20% Orbs, +20% Scrolls, +10% Silver Key & +5% / 6% / 7% / 8% Gold Key chance',
    30: '+10% Pickup Range',
    40: 'Gift Mine: Drops a gift bomb every 3s which explodes for 1000% / 1200% / 1400% / 1600% weapon dmg when enemy gets close',
    50: '+1 Starting Upgrade',
    60: '+2.5% XP Bonus',
    70: '+20% Damage to frozen enemies',
    80: 'Helping Elves: Killing enemies fills a meter, spawning 10 / 12 / 14/ 16 elves for 10s, attacking enemies with 50% weapon dmg',
    90: '+10% Area of Effect',
    100: '+5% Chance to find Lucky Wheel item',
    120: '+3% Gold Key Chance',
    140: '+1% Gold Key Chance',
  },
  'Dragon Empress': {
    'Star Passive': '2x Proj Chance',
    10: '+10% Projectile Speed',
    20: 'Festive Duplication: 15% / 20% / 25% / 30% chance to create new projectiles on hit',
    30: '+2.5% Projectile Speed',
    40: 'Enduring Flame: Every 3rd attack, projectiles burn enemies for 100% / 150% / 200% / 250% weapon dmg / sec for 3 sec',
    50: '-5% Cooldown',
    60: '+2.5% XP Bonus',
    70: '+5% Critical Hit Chance',
    80: 'Chain Reaction: Kills with main weapon fill a meter, creating new Dragon Waves on first hit, cooldown decreases by 50% and damage increases by 200% / 250% / 300% / 350%',
    90: '+35% Damage',
    100: '+10% Coin Bonus',
    120: '+1 Starting Upgrade',
    140: '+1 Magical Projectile',
  },
  'Dark Paladin': {
    'Star Passive': 'Armor',
    10: '+1 Penetration',
    20: 'Soulburn: Enemies hit by souls become cursed, spreading 100% / 120% / 140% / 160% Claymore dmg to nearby enemies for 5s',
    30: '+10% Damage',
    40: 'Soulburst Cascade: Every 8 /7 / 6 / 5 Claymore attack, the number of souls double for next attack',
    50: '+10% Projectile Speed',
    60: '+2.5% XP Bonus',
    70: '+1 Projectile',
    80: 'Soulfire Havoc: Killing enemies fills a meter, shooting souls in every direction. Number of souls increases by 2, proj spd by 50%, penetration by 2 and dmg by 50% / 70% / 90% / 110%',
    90: '-5% Cooldown',
    100: '+20% Armor',
    120: '+5% Area of Effect',
    140: '+20% Damage',
  },
  Leprechaun: {
    'Star Passive': 'Armor',
    10: '+1 Penetration',
    20: 'Soulburn: Enemies hit by souls become cursed, spreading 100% / 120% / 140% / 160% Claymore dmg to nearby enemies for 5s',
    30: '+10% Damage',
    40: 'Soulburst Cascade: Every 8 /7 / 6 / 5 Claymore attack, the number of souls double for next attack',
    50: '+10% Projectile Speed',
    60: '+2.5% XP Bonus',
    70: '+1 Projectile',
    80: 'Soulfire Havoc: Killing enemies fills a meter, shooting souls in every direction. Number of souls increases by 2, proj spd by 50%, penetration by 2 and dmg by 50% / 70% / 90% / 110%',
    90: '-5% Cooldown',
    100: '+20% Armor',
    120: '+5% Area of Effect',
    140: '+20% Damage',
  },
  'Rocket Pilot': {
    'Star Passive': 'Armor',
    10: '+1 Penetration',
    20: 'Soulburn: Enemies hit by souls become cursed, spreading 100% / 120% / 140% / 160% Claymore dmg to nearby enemies for 5s',
    30: '+10% Damage',
    40: 'Soulburst Cascade: Every 8 /7 / 6 / 5 Claymore attack, the number of souls double for next attack',
    50: '+10% Projectile Speed',
    60: '+2.5% XP Bonus',
    70: '+1 Projectile',
    80: 'Soulfire Havoc: Killing enemies fills a meter, shooting souls in every direction. Number of souls increases by 2, proj spd by 50%, penetration by 2 and dmg by 50% / 70% / 90% / 110%',
    90: '-5% Cooldown',
    100: '+20% Armor',
    120: '+5% Area of Effect',
    140: '+20% Damage',
  },
}

export default function HeroesOverview({ hero }: { hero: string }): JSX.Element {
  const rows = data[hero]
  return (
    <table>
      <th>Level</th>
      <th>Progression</th>
      {Object.entries(rows).map(([level, buff]) => (
        <tr>
          <td style={{ textAlign: 'right' }}>{level}</td>
          <td>
            {['30', '60', '90'].includes(level) ? <span style={{ color: 'magenta' }}>All Heroes:&nbsp;</span> : null}
            {level === '140' ? <span style={{ color: 'orangered' }}>All Heroes that share Faction:&nbsp;</span> : null}
            <span style={{ color: level === '80' ? 'gold' : ['20', '40'].includes(level) ? '#6792ff' : null }}>
              {buff}
            </span>
          </td>
        </tr>
      ))}
    </table>
  )
}
