const data = [
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': 'Choice 1',
		Left: 'Energy',
		Right: 'Missiles ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': 'Choice 2',
		Left: 'Paralyze ✔',
		Right: 'Burn',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '5% Stun Chance',
		Right: '10% Burn Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': 'Global',
		Left: 'Arcane Speed',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '+2.5% Projectile Speed',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': 'Evo',
		Left: 'Shoots big arcane projectiles that bounce off',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': 'Evo Choice',
		Left: 'Accelerate',
		Right: 'Penetrate ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '+25% Proj Spd',
		Right: '+1 Penetration',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Arcane Sceptor',
		Description: "Arcane Mage's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': 'Choice 1',
		Left: 'Swing ✔',
		Right: 'Stab',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '+10% Area',
		Right: '+5% Crit Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': 'Choice 2',
		Left: 'Sharp Edge',
		Right: 'Blunt Edge ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '25% Bleed Chance',
		Right: '25% Slow Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': 'Global',
		Left: 'Reinforced Grips',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '+2.5% Area',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': 'Evo',
		Left: 'Strikes in big area with magic runes, pushing back enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': 'Evo Choice',
		Left: 'Heavy Blade',
		Right: 'Light Blade ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '+20% Area',
		Right: '-10% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Rune Sword',
		Description: "Knight's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': 'Choice 1',
		Left: 'Deadeye ✔',
		Right: 'Sharpshooter',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '1% Instant Kill Chance',
		Right: '+5% Crit Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': 'Choice 2',
		Left: 'Multishot',
		Right: 'Quickdraw ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '-2% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': 'Global',
		Left: "Hunter's Haste",
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '-1% Cooldown',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': 'Evo',
		Left: 'Shoot a fan of arrows, inflicting bleeding wounds',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': 'Evo Choice',
		Left: 'Improved Explosives ✔',
		Right: 'Barbed Arrows',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '+5% Explode Chance',
		Right: '+50% Status Duration',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Dark Bow',
		Description: "Dark Ranger's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': 'Choice 1',
		Left: 'Explosive Boost',
		Right: 'Swift Deployment ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': 'Choice 2',
		Left: 'Expanded Blast ✔',
		Right: 'Enduring Napalm',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '+10% Area of Effect',
		Right: '+20% Status Duration',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': 'Global',
		Left: 'Stun Them!',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '+5% damage to stunned enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': 'Evo',
		Left: 'Bigger explosions that stun enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': 'Evo Choice',
		Left: 'Big Detonation ✔',
		Right: 'Stun Vulnerability',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '+10% Area of Effect',
		Right: '+20% damage to stunned enemies',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Big Mines',
		Description: "Crazy Tinkerer's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': 'Choice 1',
		Left: 'Bigger Fire ✔',
		Right: 'More Fire',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '+10% Area',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': 'Choice 2',
		Left: 'Flame Fury ✔',
		Right: 'Inferno Impact',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '-2.5% Cooldown',
		Right: '+10% Damage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': 'Global',
		Left: 'Burning Weapons',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '+2.5% Damage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': 'Evo',
		Left: 'Summons meteors that rain down from the sky, damaging enemies on impact',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': 'Evo Choice',
		Left: 'Armageddon ✔',
		Right: 'Asteroids',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '+50% Area',
		Right: '+4 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Meteor Staff',
		Description: "Fire Wizard's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': 'Choice 1',
		Left: 'Blizzard',
		Right: 'Avalanche ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '+5% Freeze Chance',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': 'Choice 2',
		Left: 'Frost Touch ✔',
		Right: 'Permafrost',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '+5% Freeze Chance',
		Right: '+20% Status Duration',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': 'Global',
		Left: 'Eternal Winter',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '+5% Status Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': 'Evo',
		Left: 'Summons an Ice Elemental that shoots frostbolts at enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': 'Evo Choice',
		Left: 'Hailstorm',
		Right: 'Ice Cannon ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '+5 Ice Elemental Proj',
		Right: '-40% Ice Elemental CD',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Summoner Ice Guanlets',
		Description: "Frost Wizard's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': 'Choice 1',
		Left: 'Dual Wield',
		Right: 'Big Katanas ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+5% Area',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': 'Choice 2',
		Left: 'Heartseeker',
		Right: "Blade's Finesse ✔",
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '+1% Instant Kill',
		Right: '+2.5% Crit Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': 'Global',
		Left: "Warrior's Path",
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '+2% Crit Chance',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': 'Evo',
		Left: 'Rapid attacks that make enemies explode on death',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': 'Evo Choice',
		Left: 'Heavy Hitter ✔',
		Right: 'Critmaster ',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '+5% Area of Effect',
		Right: '+5% Crit Chance',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Shadow Blades',
		Description: "BladeMaster's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': 'Choice 1',
		Left: 'Swift Spirit',
		Right: 'Beastly Domain ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: 'Beasts +25% movement ',
		Right: 'Beasts +20% Area of Effect',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': 'Choice 2',
		Left: 'Guardian Retreat ✔',
		Right: 'Feral Fury',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: 'Beast TP to you when you take damage',
		Right: 'Beasts +20% Damage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': 'Global',
		Left: 'Vital Essence',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: '+2.5% Regeneration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': 'Evo',
		Left: 'Area of thorns around the hero, slows enemies and damages them over time',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': 'Evo Choice',
		Left: 'Health Boost ✔',
		Right: 'Venomous Strike',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: '+20% Beast received healing',
		Right: '-25% poison chance, dealing damage for 3s every 1s',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Staff of the Nature God',
		Description: "Spirit Shaman's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': 'Choice 1',
		Left: 'Mighty Strike',
		Right: 'Swift Swing ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': 'Choice 2',
		Left: 'Big Strikes ✔',
		Right: 'Earthquake',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '+10% Area',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': 'Global',
		Left: 'Crushing Power',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '+2.5% Damage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': 'Evo',
		Left: 'Creates random lightnings on the map',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': 'Evo Choice',
		Left: "Tyr's Scorcher",
		Right: 'Slowing Shock ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '25% Burn',
		Right: '50% Stun',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Tyr's Hammer",
		Description: "Paladin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': 'Choice 1',
		Left: 'Wide Cuts ✔',
		Right: 'Deep Cuts',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '+10% Area',
		Right: '25% Bleed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': 'Choice 2',
		Left: 'Fast Cuts ✔',
		Right: 'Open Wounds',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '-2.5% Cooldown',
		Right: '20% Bleed Damage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': 'Global',
		Left: 'Fear of Death',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '-1% Cooldown',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': 'Evo',
		Left: "Spin an additional blade, collecting enemies' souls",
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': 'Evo Choice',
		Left: 'Crippling Spiral ✔',
		Right: 'Bloody Spiral',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '50% Slow',
		Right: '25% Bleed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Soul Harvester',
		Description: "Reaper's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': 'Choice 1',
		Left: 'Extra Rounds ✔',
		Right: 'Fast Rounds',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+10% Proj Speed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': 'Choice 2',
		Left: 'Machine Gun',
		Right: 'Quickdraw ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': 'Global',
		Left: 'Chant of Speed',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '-1% Cooldown',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': 'Evo',
		Left: 'Handcannons shoot explosive bullets',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': 'Evo Choice',
		Left: 'Ricochet',
		Right: 'Big Guns ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '+10% Duration',
		Right: '+10% Proj Speed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Handcannons',
		Description: "Pirate Queen's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': 'Choice 1',
		Left: 'Cursed Swarm ✔',
		Right: 'Bat Barrage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: 'Demon staff projectiles home into cursed enemies',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': 'Choice 2',
		Left: 'Demonic Frenzy ✔',
		Right: 'Shadowy Shroud',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: 'TLDR: Extra Projectiles',
		Right: '+10% Area of Effect',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': 'Global',
		Left: 'Mystic Duality',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: '+3% Chance to double Magical Projectiles',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': 'Evo',
		Left: 'Opens a portal randomly on the map that will free beasts',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': 'Evo Choice',
		Left: 'Portal Surge ✔',
		Right: 'Beastly Curse',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: '+1 Portal',
		Right: 'Beasts curse enemies they pass through',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Hellgate Staff',
		Description: "Warlock's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': 'Choice 1',
		Left: 'Fierce Strike',
		Right: 'Swift Exectution ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': 'Choice 2',
		Left: 'Torrential Assault',
		Right: 'Wild Rampage ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+4 Rage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': 'Global',
		Left: 'Extended Rage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: 'Rage effect duration increased by +5%',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': 'Evo',
		Left: 'Every other strike with the axes, ghost wolves appear, damaging enemies they pass through',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': 'Evo Choice',
		Left: "Wolf's Grasp ✔",
		Right: 'Bloody Fang',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: 'Wolves 50% Slow',
		Right: 'Wolves 50% Bleed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Wolf Teeth',
		Description: "Barbarian's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': 'Choice 1',
		Left: 'Strong Shots',
		Right: 'Pellets ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': 'Choice 2',
		Left: 'Toxin Bullets',
		Right: 'Kickback ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: '25% Poison Chance',
		Right: '+10% Pushback',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': 'Global',
		Left: 'Hunter Training',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: '+5% Damage to elites and bosses',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': 'Evo',
		Left: 'Birds appear, swoop down on the strongest enemies, attacking everything in their path',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': 'Evo Choice',
		Left: 'Deer Stand ✔',
		Right: 'Bear Trap',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: 'Increased dead zone area by +200%',
		Right: 'Dead zone attacks stun for 1s',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Flying Friends',
		Description: "Big Game Hunter's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': 'Choice 1',
		Left: 'Time Strike',
		Right: 'Temporal Rush ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': 'Choice 2',
		Left: 'Chrono Wave ✔',
		Right: 'Extra Disc',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: '+10% Area of Effect',
		Right: '+1 Projectile',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': 'Global',
		Left: 'Temporal Impact',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: '+5% Damage to slowed enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': 'Evo',
		Left: 'Sharp, devastating projectiles. Additional blade flying around',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': 'Evo Choice',
		Left: 'Saw Blade',
		Right: 'Heavy Frisbee ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: 'Blade has 50% Bleed Chance',
		Right: 'Blade size +50%',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chrono Blades',
		Description: "Clockwork Mage's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': 'Choice 1',
		Left: 'Air Strike',
		Right: 'Air Bender ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '+1 Projectile',
		Right: '+10% Area of Effect',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': 'Choice 2',
		Left: 'Gale Force ✔',
		Right: 'Power Boost',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '+10% Pushback',
		Right: '+10% Damage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': 'Global',
		Left: 'Wind Force',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '-1% Cooldown',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': 'Evo',
		Left: 'Airwaves bounce back from the edges of the screen',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': 'Evo Choice',
		Left: 'Eternal Gust',
		Right: 'Wind Mastery ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '+30% Effect Duration',
		Right: '+30% Projectile Speed',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'War Staff',
		Description: "Monk's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': 'Choice 1',
		Left: 'Aqua Tempo ✔',
		Right: 'Tidal Zone',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '-2.5% Cooldown',
		Right: '+10% Area of Effect',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': 'Choice 2',
		Left: 'Aqua Spray ✔',
		Right: 'Water Destruction',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '+1 Projectile',
		Right: '+10% Damage',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': 'Global',
		Left: 'Eternal Wave',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '+2.5% Effect Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': 'Evo',
		Left: 'Waves that create the ebb and flood',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': 'Evo Choice',
		Left: 'Icy Waters',
		Right: 'Torrential Strike ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '+25% Dmg to Frozen enemies',
		Right: '+10% Dmg to Slowed enemies',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Coral Trident',
		Description: "Tide Hunter's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': 'Choice 1',
		Left: 'Shadow Strike',
		Right: 'Nimble Assault ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '1.1x Dmg',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': 'Choice 2',
		Left: 'Venom Whirl',
		Right: 'Bleedy Buff ✔',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '+10% AoE',
		Right: '+5% Dmg to bleeding foes (multiplicative) ',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': 'Global',
		Left: 'Projectile Master',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '+3% Chance to double physical projectiles',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': 'Evo',
		Left: 'A huge Chakram starts flying around killing enemies',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': 'Evo Choice',
		Left: 'Extra Chakram ✔',
		Right: 'Sharp Chakram',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: 'Get an additional Chakram',
		Right: '50% chance to inflict bleed for 2s every 0.5s for 100% weapon dmg',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: 'Chakram',
		Description: "Assassin's",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Frost Queen'",
		Left: 'Some day . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Frost Queen'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Oracle'",
		Left: 'Some day . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Oracle'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Santa'",
		Left: 'Who knows . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Santa'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Dragon Empress'",
		Left: 'Who knows . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dragon Empress'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Artificer'",
		Left: 'Some day . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Artificer'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 1",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Choice 2",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Global",
		Description: "Dark Paladin'",
		Left: 'Some day . . .',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': 'Evo Choice",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Hero Weapons',
		Name: "Choice 1': '",
		Description: "Dark Paladin'",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Choice 1': '",
		Description: "''",
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': 'Choice 1',
		Left: 'Fast Shots ✔',
		Right: 'Long Shots',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '+10% Proj Speed',
		Right: '+10% Duration',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': 'Choice 2',
		Left: 'Fire Arrows',
		Right: 'Frost Arrows ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '+10% Burn Chance',
		Right: '+2.5% Freeze Chance',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': 'Global',
		Left: 'Reinforced Grips',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '+2.5% Projectile Speed',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': 'Evo',
		Left: 'The Crosswing gets an additional Projectile',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': 'Evo Choice',
		Left: 'Sleek Wing ✔',
		Right: 'Sharp Wing',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '+25% Proj Speed',
		Right: '+10% Damage',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Twin Wing',
		Description: 'Crossbow',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': 'Choice 1',
		Left: 'Orb Frenzy',
		Right: 'Big Orbs ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': 'Choice 2',
		Left: 'Incendiary',
		Right: 'Bigger Orbs ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '10% Burn Chance',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': 'Global',
		Left: 'Strong Ember',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '+2.5% Effect Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': 'Evo',
		Left: 'Creates an inner ring doing 100% more damage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': 'Evo Choice',
		Left: 'Inferno',
		Right: 'Blaze ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '+100% Status Duration',
		Right: '+20% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "' Pyro Spiral",
		Description: 'Fire Orbs',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': 'Choice 1',
		Left: 'Ammunition Box',
		Right: 'Blackpowder ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': 'Choice 2',
		Left: 'Stun Bomb',
		Right: 'Mega Burst ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '20% Stun Chance',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': 'Global',
		Left: 'Amplify',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '+2.5% Area',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': 'Evo',
		Left: 'Leave a burning area on the ground',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': 'Evo Choice',
		Left: 'Quick Reload',
		Right: 'Mass Destruction ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '-5% Cooldown',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Firebrand Rocket',
		Description: 'Bomb',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': 'Choice 1',
		Left: 'Heavenly Horizon ✔',
		Right: 'Sacred Path',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '+10% Area',
		Right: '+20% Pushback',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': 'Choice 2',
		Left: 'Stun Radiance ✔',
		Right: 'Holy Fire',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '5% Stun Chance',
		Right: '15% Burn',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': 'Global',
		Left: 'Heavenly Force',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '10% Pushback',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': 'Evo',
		Left: 'Enemies hit by the weapon are slowed by 20%',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': 'Evo Choice',
		Left: 'Bloodmoon ✔',
		Right: 'Swift Shadows',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '+30% Regeneration',
		Right: '-5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: "Vampire's Grasp",
		Description: 'Divine Aura',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': 'Choice 1',
		Left: 'Storming Blades ✔',
		Right: 'Precision Spin',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+5% Crit Chance',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': 'Choice 2',
		Left: 'Stunning Impact ✔',
		Right: 'Whirling Blades',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: '20% Stun',
		Right: 'Size Increased',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': 'Global',
		Left: 'Dual Returns',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: '+3% Double Physical Projectiles',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': 'Evo',
		Left: 'Herorang leaves a circular burning ring around the hero',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': 'Evo Choice',
		Left: 'Knockback ✔',
		Right: 'Massive Destruction ',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: 'Pushback',
		Right: '+4 Projectiles',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Whirlwind',
		Description: 'Boomerang',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': 'Choice 1',
		Left: 'Lasting Power ',
		Right: 'Mighty Burst ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '+10% Effect Duration',
		Right: '10% Damage',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': 'Choice 2',
		Left: 'Fiery Inferno',
		Right: 'Additional Flares ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '25% Burn',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': 'Global',
		Left: 'Prolonged Flame',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '+2.5% Effect Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': 'Evo',
		Left: 'Enemies are slowed by 90% while Death Ray is locked on them',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': 'Evo Choice',
		Left: 'Scorching Fury ✔',
		Right: 'Swift Recharge',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '+20% Damage to Burn',
		Right: '-5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Fiery Inferno',
		Description: 'Arcane Staff',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': 'Choice 1',
		Left: 'Frostbolt ',
		Right: 'Quick Freeze ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '+1 Projectiles',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': 'Choice 2',
		Left: 'Frostbolt 2 ✔',
		Right: 'Enduring Chill ',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '+1 Projectiles',
		Right: '+20% Status Duration',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': 'Global',
		Left: 'Frozen Fury',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '+5% Frozen Damage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': 'Evo',
		Left: '+1 Penetration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': 'Evo Choice',
		Left: 'Ice Barrage ✔',
		Right: 'Eternal Frost ',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: '+20% Status Duration',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Piercing Ice',
		Description: 'Ice Wand',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': 'Choice 1',
		Left: 'Powerful Blow',
		Right: 'Quick Strike ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '-2.5% Cooldown',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': 'Choice 2',
		Left: 'Hammer Time',
		Right: 'Toolbox ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: 'Size Increase',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': 'Global',
		Left: 'Devasting Force',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: '+2.5% Damage',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': 'Evo',
		Left: '+20% Pushback',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': 'Evo Choice',
		Left: 'Rapid Assault ✔',
		Right: 'Massive Impact ',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: '-5% Cooldown',
		Right: '10% Stun',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Hammer Force',
		Description: 'Hammer',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': 'Choice 1',
		Left: 'High Voltage',
		Right: 'Zapdash ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '+10% Duration',
		Right: '+10% Proj Spd',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': 'Choice 2',
		Left: 'Blazebolt',
		Right: 'Overload ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '10% Burn Chance',
		Right: '+10% Damage',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': 'Global',
		Left: 'Lightspeed',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '+2.5% Effect Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': 'Evo',
		Left: 'Reduces damage reduction between jumps',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': 'Evo Choice',
		Left: 'Shocker',
		Right: 'Electric Surge ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '+50% Status Duration',
		Right: '+2 Projectiles',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Chain Stability',
		Description: 'Chain Lightning',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': 'Choice 1',
		Left: 'Hot Wind',
		Right: "Dragon's Blaze ✔",
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '+10% Damage',
		Right: '+10% Area',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': 'Choice 2',
		Left: "Dragon's Ignition",
		Right: 'Long Wind ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '25% Burn',
		Right: '10% Effect Duration',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': 'Global',
		Left: 'Fire Vulnerability',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '+5% Damage to Burn',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': 'Evo',
		Left: "Dragon's Inferno leaves a burning area behind",
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': 'Evo Choice',
		Left: 'Endless Flames',
		Right: 'Eternal Inferno ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '+20% Status Duration',
		Right: '10% Effect Duration',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Dragon Destruction',
		Description: "Dragon's Breath",
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': 'Choice 1',
		Left: 'Secret Pocket',
		Right: 'Rear Damage ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': '',
		Left: '+2 Projectiles',
		Right: 'All darts Shoot Backward',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': 'Choice 2',
		Left: 'Front Damage',
		Right: 'Big Darts ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': '',
		Left: 'All darts Shoot Front',
		Right: 'Size Increase',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': 'Global',
		Left: 'Strong Venom',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': '',
		Left: '+5% Status Duration',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': 'Evo',
		Left: 'Enemies hit by the weapon are slowed by 25%',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': '',
		Left: '',
		Right: '',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': 'Evo Choice',
		Left: 'Improved Formula',
		Right: 'Toxic Outbreak ✔',
	},
	{
		'Weapon Type': 'Forged Stage Weapons',
		Name: 'Venomous Stasis',
		Description: 'Poison Darts',
		'Choice 1': '',
		Left: '+50% Status Duration',
		Right: '+2 Projectiles',
	},
]
